const consts = {
  BUTTON_GREEN: '#6ED47C',
  BUTTON_ORANGE: '#FFC700',
  BOX_YELLOW: '#FFC700',
  TEXT_ORANGE: '#F95A2C',
  TEXT_GRAY: '#474A57',
  TEXT_LIGHT_GRAY: '#969BAB',
  BOX_PEACH: '#FF743C',
  BOX_DARK_GREY: '#2D3652',
  BOX_PINK: '#D33367',
  BOX_IMAGE_SIZE: 60,
  WARNING_RED: 'red',
  WARNING_BOX_RED: '#ff5e5e',
  CIRCLE_ORANGE: '#FFBD12',
  CIRCLE_GREEN: '#00C6AE',
  CIRCLE_PINK: '#FF89BB',
  TAG_YELLOW: '#FFF4CC',
  TAG_GREEN: '#D6FCF7',
  DOT_ORANGE: '#F95A2C',
  HISTORY_BOX_PINK: '#FFF3F8',
  HISTORY_BOX_GREEN: '#D6FCF7'
}

export default consts